#!/usr/bin/env python3
"""Per-session journal files and the generated rollup. Stdlib only.

    python build_journal.py --knowledge ~/.claude/knowledge            # regenerate journal.md
    python build_journal.py --knowledge ~/.claude/knowledge --check    # exit 1 on drift
    python build_journal.py --knowledge ~/.claude/knowledge --migrate  # one-time split
    python build_journal.py --selftest

Source of truth: one file per session in knowledge/journal/, named
YYYY-MM-DD-HHMM-<slug>.md, with frontmatter

    date: 2026-09-17
    time: "14:32"
    topic: "Fernwood / route sheet"
    summary: "one telegraphic line: what was decided or built"
    next: "one line: what happens next"

and the full entry as the body. Two devices writing on the same day produce two
files, never a conflict. The summary and next lines are what the root MEMORY.md
Recent block shows; the body is one hop down, whole.

Output: knowledge/journal.md, generated, newest first: a one-line-per-session
list, then every entry whole. Tier C, for grepping an investigation.

--migrate splits a hand-appended journal.md (one "- YYYY-MM-DD ... " line per
session) into the per-session files. The clock time comes from git blame on the
line's commit, since the old lines carry none; topic, summary and next are
parsed mechanically and are meant to be edited where the parse is poor. Nothing
is lost: the whole original line is the body of each file. Run once, review,
regenerate, commit.
"""
import argparse
import datetime as dt
import re
import subprocess
import sys
import tempfile
from pathlib import Path

HEADER = ("<!-- generated by build_journal.py from knowledge/journal/*.md; add a session "
          "as a new file there and regenerate. Hand edits are overwritten. -->")
ENTRY_RE = re.compile(r"^- (?P<date>\d{4}-\d{2}-\d{2})\s*(?:\((?P<qual>[^)]*)\))?\s*(?:—|-)?\s*(?P<rest>.*)$")
NEXT_RE = re.compile(r"\b(?:Next|NEXT)\s*[:,]\s*(?P<next>.+?)\s*$")
FILE_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})-(\d{4})-(.+)\.md$")


def _fm():
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    import build_index
    return build_index


# ----------------------------------------------------------------- parsing
def parse_line(line):
    """Old-style journal line -> dict(date, qual, topic, summary, next, body)."""
    m = ENTRY_RE.match(line)
    if not m:
        return None
    rest = m.group("rest").strip()
    topic, what = "", rest
    for sep in (" — ", " - ", ": "):
        head, s, tail = rest.partition(sep)
        if s and 0 < len(head) <= 70:
            topic, what = head.strip(), tail.strip()
            break
    nxt = ""
    nm = NEXT_RE.search(what)
    if nm:
        nxt = nm.group("next").rstrip(".")
        what_wo_next = what[:nm.start()].rstrip(" .;")
    else:
        what_wo_next = what
    sent = re.split(r"(?<=[.;])\s+(?=[A-Z`*\"'(])", what_wo_next, maxsplit=1)[0].strip()
    if len(sent) > 240:
        sent = sent[:240].rsplit(" ", 1)[0] + " …"
    return {"date": m.group("date"), "qual": (m.group("qual") or "").strip(),
            "topic": topic, "summary": sent.rstrip("."), "next": nxt,
            "body": line[2:].strip()}


def slugify(s, n=40):
    s = re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")
    return (s[:n].rstrip("-") or "session")


def blame_times(path):
    """line number (1-based) -> local datetime of the commit that added it."""
    try:
        out = subprocess.run(["git", "blame", "--line-porcelain", "--", path.name],
                             cwd=path.parent, capture_output=True, text=True,
                             encoding="utf-8", check=True).stdout
    except (subprocess.CalledProcessError, FileNotFoundError):
        return {}
    times, n, t = {}, 0, None
    for line in out.splitlines():
        if line.startswith("committer-time "):
            t = dt.datetime.fromtimestamp(int(line.split()[1]))
        elif line.startswith("\t"):
            n += 1
            if t:
                times[n] = t
    return times


# --------------------------------------------------------------- migration
def _write_session(jdir, e, hhmm, used):
    """Write one session file for a parsed entry; returns the stem."""
    stem = f"{e['date']}-{hhmm}-{slugify(e['topic'] or e['summary'])}"
    k, base = 2, stem
    while stem in used or (jdir / f"{stem}.md").exists():
        stem = f"{base}-{k}"
        k += 1
    used.add(stem)
    q = _fm().yaml_quote
    text = ("---\n"
            f"date: {e['date']}\n"
            f"time: {q(hhmm[:2] + ':' + hhmm[2:])}\n"
            f"topic: {q(e['topic'])}\n"
            f"summary: {q(e['summary'])}\n"
            f"next: {q(e['next'])}\n"
            "---\n\n" + e["body"] + "\n")
    (jdir / f"{stem}.md").write_text(text, encoding="utf-8", newline="\n")
    return stem


def _hhmm(times, n, e, now=None):
    t = times.get(n)
    if t and t.date().isoformat() == e["date"]:
        return t.strftime("%H%M")
    if now and now.date().isoformat() == e["date"]:
        return now.strftime("%H%M")
    return "0000"


def migrate(know):
    know = Path(know)
    src = know / "journal.md"
    if not src.is_file():
        return []
    jdir = know / "journal"
    jdir.mkdir(exist_ok=True)
    times = blame_times(src)
    written, used = [], set()
    for n, line in enumerate(src.read_text(encoding="utf-8").splitlines(), 1):
        e = parse_line(line)
        if e:
            written.append(_write_session(jdir, e, _hhmm(times, n, e), used))
    return written


def rescue(know, now=None):
    """Self-healing: a session that appended a line to the generated journal.md
    by habit gets that line turned into a session file instead of losing it on
    the next regenerate. Returns the stems written. Runs before every write."""
    know = Path(know)
    src, jdir = know / "journal.md", know / "journal"
    if not src.is_file() or not jdir.is_dir():
        return []
    ents = entries(know)
    generated = set(render(ents).splitlines())
    bodies = {e["body"] for e in ents}
    # a line in the generated shape (date then HH:MM) was rendered from a session file:
    # either current, or stale because that file was edited or deleted. Never rescue
    # it; only the old hand-written shape ("- date — topic — text") is a habit append.
    times = blame_times(src)
    written, used = [], set()
    for n, line in enumerate(src.read_text(encoding="utf-8").splitlines(), 1):
        e = parse_line(line)
        if re.match(r"^- \d{4}-\d{2}-\d{2} \d{2}:\d{2}\b", line):
            continue
        if e and line not in generated and e["body"] not in bodies:
            written.append(_write_session(jdir, e, _hhmm(times, n, e, now or dt.datetime.now()), used))
    return written


# ----------------------------------------------------------------- loading
def entries(know):
    """Per-session files -> list of dicts, oldest first. Empty if no journal/ dir."""
    jdir = Path(know) / "journal"
    if not jdir.is_dir():
        return []
    fm = _fm()
    out = []
    for p in sorted(jdir.glob("*.md"), key=lambda p: p.stem):   # stem: "a-2" after "a"
        if p.name in ("INDEX.md", "TOPIC.md"):
            continue
        lines, body = fm.split_frontmatter(p.read_text(encoding="utf-8"))
        d = fm.parse_frontmatter(lines)
        m = FILE_RE.match(p.name)
        d.setdefault("date", m.group(1) if m else "????-??-??")
        d.setdefault("time", f"{m.group(2)[:2]}:{m.group(2)[2:]}" if m else "")
        d.setdefault("topic", m.group(3).replace("-", " ") if m else p.stem)
        d.setdefault("summary", "")
        d.setdefault("next", "")
        d["body"], d["file"] = body.strip(), p.name
        out.append(d)
    return out


def one_line(e):
    s = f"- {e['date']} {e['time']} {e['topic']} — {e['summary']}".rstrip(" —")
    return s + (f". Next: {e['next']}" if e["next"] else "")


# --------------------------------------------------------------- rendering
def render(es):
    L = [HEADER, "", "# Session journal", "",
         "Generated from `journal/*.md`, newest first: one line per session, then every",
         "entry whole. Add a session as a new file there (see templates/journal-entry.md),",
         "then regenerate. Never edit this file.", "",
         f"## Sessions ({len(es)})", ""]
    L += [one_line(e) for e in reversed(es)]
    L += ["", "## Entries", ""]
    for e in reversed(es):
        L += [f"### {e['date']} {e['time']} — {e['topic']}  ·  `journal/{e['file']}`", "",
              e["body"], ""]
    return "\n".join(L)


def build(know):
    es = entries(know)
    return {"journal.md": render(es)} if es else {}


def check(know, generated):
    return [rel for rel, text in generated.items()
            if not (Path(know) / rel).is_file()
            or (Path(know) / rel).read_text(encoding="utf-8") != text]


def write(know, generated=None):
    """Rescue stray appends, then (re)build and write. Never overwrites a hand-appended line."""
    if rescue(know):
        generated = None                      # sources changed; rebuild
    for rel, text in (generated or build(know)).items():
        (Path(know) / rel).write_text(text, encoding="utf-8", newline="\n")


# ----------------------------------------------------------------- selftest
def selftest():
    e = parse_line("- 2026-09-17 (close) — Fernwood / route sheet: approved as drafted. "
                   "Rewrote §11. Next: Phase 0, write measure.py.")
    assert e["date"] == "2026-09-17" and e["qual"] == "close", e
    assert e["topic"] == "Fernwood / route sheet" and e["summary"] == "approved as drafted", e
    assert e["next"] == "Phase 0, write measure.py", e
    assert e["body"].startswith("2026-09-17 (close)")
    e = parse_line("- 2026-09-14 Widgets: rechecked Tier A. Dec 14 is the play.")
    assert e["topic"] == "Widgets" and e["next"] == "" and e["summary"] == "rechecked Tier A", e
    assert parse_line("# heading") is None
    assert slugify("Fernwood / route sheet") == "fernwood-route-sheet"

    with tempfile.TemporaryDirectory() as d:
        know = Path(d)
        (know / "journal.md").write_text(
            "# J\n\n- 2026-01-01 — topic a — did a. Next: b.\n"
            "- 2026-01-01 — topic a — did a again. Next: c.\n"
            "- 2026-01-02 (eve) — topic b — did b\n", encoding="utf-8")
        names = migrate(know)                      # no git here: time falls back to 0000
        assert names == ["2026-01-01-0000-topic-a", "2026-01-01-0000-topic-a-2",
                         "2026-01-02-0000-topic-b"], names
        es = entries(know)
        assert [x["summary"] for x in es] == ["did a", "did a again", "did b"], es
        assert es[0]["next"] == "b" and es[2]["next"] == ""
        assert es[2]["body"] == "2026-01-02 (eve) — topic b — did b"
        gen = build(know)
        text = gen["journal.md"]
        assert text.startswith(HEADER) and "## Sessions (3)" in text
        assert text.index("2026-01-02 00:00 topic b") < text.index("2026-01-01 00:00 topic a — did a again")
        assert "- 2026-01-01 00:00 topic a — did a. Next: b" in text
        write(know, gen)
        assert check(know, gen) == []
        (know / "journal.md").write_text("x", encoding="utf-8")
        assert check(know, build(know)) == ["journal.md"]
        # self-healing: a line appended to the generated file by habit becomes a session file
        write(know)
        with open(know / "journal.md", "a", encoding="utf-8") as fh:
            fh.write("- 2026-01-05 — topic d — did d by habit. Next: e.\n")
        assert check(know, build(know)) == ["journal.md"]          # drift is visible
        stems = rescue(know, now=dt.datetime(2026, 1, 5, 14, 30))
        assert stems == ["2026-01-05-1430-topic-d"], stems
        assert rescue(know) == []                                   # idempotent
        write(know)
        text = (know / "journal.md").read_text(encoding="utf-8")
        assert "- 2026-01-05 14:30 topic d — did d by habit. Next: e" in text
        assert "2026-01-05 — topic d — did d by habit. Next: e." in text  # body kept whole
        assert check(know, build(know)) == []
        # editing a session file's summary makes its old rollup line an orphan; that is
        # drift to regenerate, never a line to rescue into a duplicate session file
        p = know / "journal" / "2026-01-05-1430-topic-d.md"
        p.write_text(p.read_text(encoding="utf-8").replace("did d by habit", "did d on purpose"), encoding="utf-8")
        assert check(know, build(know)) == ["journal.md"]
        assert rescue(know) == [], "stale rollup line was rescued"
        write(know)
        p.unlink()                                                  # deleted on purpose
        assert rescue(know) == [], "deleted session resurrected from the stale rollup"
        write(know)
        # a hand-written new session file with only summary is fine
        (know / "journal" / "2026-01-03-0915-topic-c.md").write_text(
            '---\ndate: 2026-01-03\ntime: "09:15"\ntopic: "topic c"\nsummary: "did c"\nnext: ""\n---\n\nlong body\n',
            encoding="utf-8")
        assert next(e for e in entries(know) if e["topic"] == "topic c")["body"] == "long body"
    print("selftest ok")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--knowledge")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--migrate", action="store_true")
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args()
    if a.selftest:
        return selftest()
    if not a.knowledge:
        ap.error("--knowledge is required")
    know = Path(a.knowledge).expanduser()
    if a.migrate:
        names = migrate(know)
        print(f"wrote {len(names)} session files into {know / 'journal'}")
        return 0
    gen = build(know)
    if not gen:
        print("no journal/ folder; nothing to build")
        return 0
    if a.check:
        drift = check(know, gen)
        print("journal.md matches journal/" if not drift else "journal.md stale; run without --check")
        return 1 if drift else 0
    write(know, gen)
    print(f"wrote journal.md ({len(gen['journal.md']):,} chars, {len(entries(know))} sessions)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
