#!/usr/bin/env python3
"""Generate the memory indexes: one INDEX.md per topic folder and a root
MEMORY.md that is recency plus routes. Stdlib only.

    python build_index.py --knowledge ~/.claude/knowledge            # regenerate
    python build_index.py --knowledge ~/.claude/knowledge --check    # exit 1 on drift
    python build_index.py --knowledge ~/.claude/knowledge --migrate  # one-time, see below
    python build_index.py --selftest

Sources of truth (never edit a generated file; edit these and regenerate):

  knowledge/<topic>/TOPIC.md      frontmatter: title, description, keywords
  knowledge/<topic>/*.md          facts; frontmatter: title, description,
                                  metadata.type, optional keywords
  knowledge/journal.md            one dated line per session (or journal/*.md,
                                  one file per session, once Phase 1 step 4 lands)
  git history                     recency = last commit date touching the file,
                                  never mtime (a fresh clone resets every mtime)

Outputs, each stamped with a generated-file header:

  knowledge/<topic>/INDEX.md      every fact in the folder, whole hook text,
                                  grouped by type, newest first
  knowledge/MEMORY.md             Recent (last N facts + last M journal entries)
                                  and Routes (topic, triggers, index path, count)

--migrate is the one-time step for a workspace whose MEMORY.md was hand-curated:
it copies each index line's title and hook into that fact's frontmatter as
`title:` and `description:`, so the file becomes the source of truth. It prints
any old description carrying words found in neither the hook nor the body, for
review by hand. Run it once, review, regenerate, commit.
"""
import argparse
import datetime as dt
import re
import subprocess
import sys
import tempfile
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))   # sibling build_journal

HEADER = ("<!-- generated by build_index.py from fact frontmatter and git history; "
          "edit the fact files or TOPIC.md, then regenerate. Hand edits are overwritten. -->")
# not facts: the generated files, the topic config, and the topic's own state files
# (decision log, task roster, rules) that live beside the facts from Phase 3 on
STRUCTURAL = {"MEMORY.md", "INDEX.md", "TOPIC.md", "journal.md", "LOG.md", "TASKS.md", "RULES.md"}
TYPE_ORDER = ["user", "feedback", "project", "reference"]
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
INDEX_LINE_RE = re.compile(r"^- \[(?P<title>.*?)\]\((?P<path>[^)]+\.md)\) — (?P<hook>.*)$")
JOURNAL_LINE_RE = re.compile(r"^- \d{4}-\d{2}-\d{2}")
# One place for the generation options, shared by main() and the --check drift test.
# Change a default here by decision, never per run.
DEFAULTS = {"n_facts": 10, "n_journal": 3, "titles": False,
            # a `project` fact untouched this long shows title-only in its topic index
            # (the hook is one hop away in the file); feedback, reference and user facts
            # always keep the hook, because for those the hook is the rule
            "hook_days": 30}


# ---------------------------------------------------------------- frontmatter
def split_frontmatter(text):
    """-> (frontmatter_lines or None, body_text)."""
    m = re.match(r"---\r?\n(.*?)\r?\n---\r?\n?", text, re.S)
    if not m:
        return None, text
    return m.group(1).splitlines(), text[m.end():]


def yaml_unquote(v):
    v = v.strip()
    if len(v) >= 2 and v[0] == v[-1] and v[0] in "\"'":
        inner = v[1:-1]
        if v[0] == '"':
            return inner.replace('\\"', '"').replace("\\\\", "\\")
        return inner.replace("''", "'")
    return v


def yaml_quote(v):
    return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'


def parse_list(v):
    v = v.strip()
    if v.startswith("[") and v.endswith("]"):
        v = v[1:-1]
    return [yaml_unquote(x) for x in v.split(",") if x.strip()]


def parse_frontmatter(lines):
    """Flat parse: top-level `key: value` plus `type:` from an indented metadata block."""
    d = {}
    for line in lines or []:
        m = re.match(r"^(\s*)([A-Za-z_][\w-]*):\s*(.*)$", line)
        if not m:
            continue
        indent, key, val = m.groups()
        if indent:
            if key == "type" and "type" not in d:
                d["type"] = yaml_unquote(val)
            continue
        if key == "keywords":
            d["keywords"] = parse_list(val)
        elif key == "type":
            d.setdefault("type", yaml_unquote(val))
        else:
            d[key] = yaml_unquote(val)
    return d


def set_frontmatter_keys(text, updates):
    """Rewrite top-level keys in the frontmatter, inserting missing ones after
    `name:` (or at the top). Everything else is preserved byte for byte."""
    fm, body = split_frontmatter(text)
    if fm is None:
        fm = []
    out, done = [], set()
    for line in fm:
        m = re.match(r"^([A-Za-z_][\w-]*):", line)
        if m and m.group(1) in updates:
            out.append(f"{m.group(1)}: {yaml_quote(updates[m.group(1)])}")
            done.add(m.group(1))
        else:
            out.append(line)
    missing = [k for k in updates if k not in done]
    if missing:
        pos = next((i + 1 for i, l in enumerate(out) if l.startswith("name:")), 0)
        for k in reversed(missing):
            out.insert(pos, f"{k}: {yaml_quote(updates[k])}")
    return "---\n" + "\n".join(out) + "\n---\n" + body


# ------------------------------------------------------------------- loading
def git_dates(know):
    """rel path (posix, relative to know) -> last commit date. Uncommitted -> absent."""
    try:
        top = subprocess.run(["git", "rev-parse", "--show-toplevel"], cwd=know,
                             capture_output=True, text=True, encoding="utf-8", check=True
                             ).stdout.strip()
        log = subprocess.run(["git", "log", "--format=%cs", "--name-only", "--", "."],
                             cwd=know, capture_output=True, text=True, encoding="utf-8",
                             check=True).stdout
    except (subprocess.CalledProcessError, FileNotFoundError):
        return {}
    prefix = know.resolve().relative_to(Path(top).resolve()).as_posix()
    prefix = "" if prefix == "." else prefix + "/"
    dates, date = {}, None
    for line in log.splitlines():
        if DATE_RE.match(line):
            date = line
        elif line.strip() and line.startswith(prefix):
            dates.setdefault(line[len(prefix):], date)
    return dates


def sub_indexes(topic_dir):
    """Hand-maintained mirror indexes one tier down: <topic>/<sub>/INDEX.md whose
    frontmatter carries title, description, keywords and `mirrors:` (the human folder
    it describes). They index human files, which have no frontmatter to generate
    from, so they are written by hand and never carry the generated header.
    -> {sub_dir_name: meta}"""
    subs = {}
    for s in sorted(p for p in Path(topic_dir).iterdir() if p.is_dir() and not p.name.startswith(".")):
        ip = s / "INDEX.md"
        if not ip.is_file():
            continue
        fm, _ = split_frontmatter(ip.read_text(encoding="utf-8"))
        if fm is None:
            continue
        m = parse_frontmatter(fm)
        m.setdefault("title", s.name)
        m.setdefault("description", "")
        m.setdefault("keywords", [])
        m.setdefault("mirrors", "")
        subs[s.name] = m
    return subs


def load(know, today):
    know = Path(know)
    today = str(today)                  # git dates are ISO strings; an uncommitted fact sorts as today
    dates = git_dates(know)
    topics, facts = {}, {}
    for d in sorted(p for p in know.iterdir() if p.is_dir() and not p.name.startswith(".")):
        if d.name == "journal":
            continue
        tp = d / "TOPIC.md"
        meta = parse_frontmatter(split_frontmatter(tp.read_text(encoding="utf-8"))[0]) \
            if tp.is_file() else {}
        meta.setdefault("title", d.name)
        meta.setdefault("description", "")
        meta.setdefault("keywords", [])
        meta["has_topic_md"] = tp.is_file()
        meta["subs"] = sub_indexes(d)
        # git dates of everything under this topic, for the task roster's Recent block
        meta["dates"] = {k[len(d.name) + 1:]: v for k, v in dates.items() if k.startswith(d.name + "/")}
        topics[d.name] = meta
        for p in sorted(d.glob("*.md")):
            if p.name in STRUCTURAL:
                continue
            rel = f"{d.name}/{p.name}"
            fm, body = split_frontmatter(p.read_text(encoding="utf-8"))
            f = parse_frontmatter(fm)
            f["rel"], f["topic"], f["body"] = rel, d.name, body
            f.setdefault("title", re.sub(r"^(user|feedback|project|reference)_", "",
                                         p.stem).replace("_", " ").capitalize())
            f.setdefault("description", "")
            f.setdefault("type", "?")
            f["date"] = dates.get(rel)           # None = not committed yet
            f["sort_date"] = f["date"] or today  # uncommitted sorts as newest
            facts[rel] = f
    return topics, facts


def journal_entries(know):
    """One line per session, oldest first. Per-session files win over journal.md."""
    know = Path(know)
    if (know / "journal").is_dir():
        import build_journal
        return [build_journal.one_line(e) for e in build_journal.entries(know)]
    jf = know / "journal.md"
    if not jf.is_file():
        return []
    return [l for l in jf.read_text(encoding="utf-8").splitlines() if JOURNAL_LINE_RE.match(l)]


# ---------------------------------------------------------------- rendering
def fact_line(f, link, today=None, hook_days=None):
    # An uncommitted fact renders with today's date, which is what its commit date
    # will be; rendering "uncommitted" made the commit itself drift the index.
    if hook_days is not None and today and f.get("type") == "project" and f.get("date") \
            and (dt.date.fromisoformat(str(today)) - dt.date.fromisoformat(f["date"])).days > hook_days:
        return f"- {f['sort_date']} [{f['title']}]({link})"
    return f"- {f['sort_date']} [{f['title']}]({link}) — {f['description']}"


def render_topic(topic, meta, facts, today=None, hook_days=None):
    L = [HEADER, "", f"# {meta['title']} — {meta['description']}".rstrip(" —"), ""]
    if meta["keywords"]:
        L += [f"Triggers: {', '.join(meta['keywords'])}", ""]
    if meta.get("tasks"):
        o, dn, n = meta["tasks"]
        L += [f"Tasks: [TASKS.md](TASKS.md) — generated roster, {o} open in {n} initiatives "
              f"(detail in `initiatives/`); decision log: [LOG.md](LOG.md)", ""]
    by_type = defaultdict(list)
    for f in facts:
        by_type[f["type"]].append(f)
    for ty in TYPE_ORDER + sorted(k for k in by_type if k not in TYPE_ORDER):
        if ty not in by_type:
            continue
        if ty == "project" and hook_days is not None:
            L.append(f"## {ty} (a fact untouched {hook_days}+ days shows its title only; the hook is in the file)")
        else:
            L.append(f"## {ty}")
        for f in sorted(by_type[ty], key=lambda f: (f["sort_date"], f["rel"]), reverse=True):
            L.append(fact_line(f, Path(f["rel"]).name, today, hook_days))
        L.append("")
    if not facts:
        L += ["(no facts yet)", ""]
    if meta.get("subs"):
        # Nested tier: the topic routes on to its mirror indexes the same way the root
        # routes to topics. The root Routes table still points only at topic folders.
        # Title and triggers only: the description and the mirrored folder's name are in
        # each mirror index's own frontmatter, one hop down (Phase 6 lever, 2026-09-19).
        L += ["## Routes — mirror indexes one tier down (hand-maintained, one per human folder)", "",
              "| Mirror index | Triggers |", "|---|---|"]
        for s, m in meta["subs"].items():
            kws = ", ".join(m["keywords"]) if m["keywords"] else "(no keywords)"
            L.append(f"| [{m['title']}]({s}/INDEX.md) | {kws} |")
        L.append("")
    return "\n".join(L)


def render_root(topics, facts, journal, n_facts, n_journal, titles=False):
    L = [HEADER, "", "# Memory", "",
         "Root is recency + routes only. Every fact lives one hop down in its topic INDEX.md;",
         "when a route trigger comes up in the conversation, open that index, then the fact.",
         "Memory writes: add or edit a fact file, run build_index.py, commit both. Never edit",
         "this file or an INDEX.md by hand.", "",
         f"## Recent — last {n_facts} facts touched (git commit date) and last {n_journal} journal entries", ""]
    recent = sorted(facts.values(), key=lambda f: (f["sort_date"], f["rel"]), reverse=True)
    for f in recent[:n_facts]:
        L.append(fact_line(f, f["rel"]))
    if n_journal and journal:
        L.append("")
        L += journal[-n_journal:]
    L += ["", "## Routes", "", "| Topic | Triggers | Index | Facts |", "|---|---|---|---:|"]
    order = sorted(topics, key=lambda t: (t == "archive", topics[t]["title"].lower()))
    for t in order:
        m = topics[t]
        kws = ", ".join(m["keywords"]) if m["keywords"] else "(no TOPIC.md — add one)"
        n = sum(1 for f in facts.values() if f["topic"] == t)
        L.append(f"| {m['title']} — {m['description']} | {kws} | [{t}/INDEX.md]({t}/INDEX.md) | {n} |")
    if titles:
        # Recall safety net: every fact's title, no hooks, so a
        # session can see that a fact about X exists even when no route trigger fired.
        L += ["", "## All facts, titles only (open the topic INDEX.md for the hook)", ""]
        for t in order:
            names = sorted(f["title"] for f in facts.values() if f["topic"] == t)
            if names:
                L.append(f"- **{topics[t]['title']}:** " + " · ".join(names))
    L.append("")
    return "\n".join(L)


def build(know, n_facts, n_journal, today, titles=False, hook_days=DEFAULTS["hook_days"]):
    """-> {relpath: text} for every generated file."""
    know = Path(know)
    topics, facts = load(know, today)
    # facts may add keywords; union into their topic's triggers. Mirror-index keywords
    # are NOT unioned into the root row: with sixteen mirror indexes that was +600
    # tokens on every session in every topic, and the topic's own triggers already
    # catch the conversation; the hook lifts the topic on a sub-folder hit anyway.
    for f in facts.values():
        for k in f.get("keywords", []):
            if k not in topics[f["topic"]]["keywords"]:
                topics[f["topic"]]["keywords"].append(k)
    out = {}
    for t, meta in topics.items():
        if (know / t / "initiatives").is_dir():      # task roster, generated in the same pass
            import build_tasks
            out[f"{t}/TASKS.md"] = build_tasks.render(know / t, meta["title"], meta["dates"], today)
            meta["tasks"] = build_tasks.summary(know / t)
        out[f"{t}/INDEX.md"] = render_topic(t, meta, [f for f in facts.values() if f["topic"] == t],
                                            today, hook_days)
    out["MEMORY.md"] = render_root(topics, facts, journal_entries(know), n_facts, n_journal, titles)
    if (know / "journal").is_dir():            # rollup is generated in the same pass
        import build_journal
        out.update(build_journal.build(know))
    return out


def write(know, generated):
    for rel, text in generated.items():
        p = Path(know) / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8", newline="\n")


def check(know, generated):
    drift = []
    for rel, text in generated.items():
        p = Path(know) / rel
        if not p.is_file() or p.read_text(encoding="utf-8") != text:
            drift.append(rel)
    return drift


# ---------------------------------------------------------------- migration
WORD_RE = re.compile(r"[a-z0-9][a-z0-9.@/-]{3,}")


def migrate(know):
    """Copy title + hook from a hand-curated MEMORY.md into each fact's frontmatter."""
    know = Path(know)
    index = know / "MEMORY.md"
    if not index.is_file():
        return [], []
    changed, flagged = [], []
    for line in index.read_text(encoding="utf-8").splitlines():
        m = INDEX_LINE_RE.match(line)
        if not m:
            continue
        rel = m.group("path").replace("\\", "/")
        p = know / rel
        if not p.is_file():
            continue
        text = p.read_text(encoding="utf-8")
        fm, body = split_frontmatter(text)
        old = parse_frontmatter(fm).get("description", "")
        title, hook = m.group("title"), m.group("hook")
        if old and old != hook:
            have = set(WORD_RE.findall((hook + " " + body).lower()))
            lost = [w for w in WORD_RE.findall(old.lower()) if w not in have]
            if lost:
                flagged.append((rel, old, lost))
        new = set_frontmatter_keys(text, {"title": title, "description": hook})
        if new != text:
            p.write_text(new, encoding="utf-8", newline="\n")
            changed.append(rel)
    return changed, flagged


# ----------------------------------------------------------------- selftest
def selftest():
    with tempfile.TemporaryDirectory() as d:
        know = Path(d) / "knowledge"
        (know / "alpha").mkdir(parents=True)
        (know / "beta").mkdir()
        (know / "alpha" / "TOPIC.md").write_text(
            '---\ntitle: Alpha\ndescription: "first topic"\nkeywords: [alpha, one]\n---\n', encoding="utf-8")
        (know / "alpha" / "feedback_a.md").write_text(
            '---\nname: feedback_a\ndescription: "old words here"\nmetadata:\n  type: feedback\n'
            'keywords: [extra]\n---\n\nbody mentions nothing.\n', encoding="utf-8")
        (know / "alpha" / "project_b.md").write_text(
            '---\nname: project_b\ndescription: b desc\nmetadata:\n  type: project\n---\n\nb body\n',
            encoding="utf-8")
        (know / "beta" / "reference_c.md").write_text(
            '---\nname: reference_c\ndescription: "c \\"quoted\\" desc"\nmetadata:\n  type: reference\n---\n\nc\n',
            encoding="utf-8")
        (know / "journal.md").write_text("# J\n\n- 2026-01-01 — t — one\n- 2026-01-02 — t — two\n",
                                         encoding="utf-8")
        (know / "MEMORY.md").write_text(
            "# M\n- [A title](alpha/feedback_a.md) — curated hook for a\n"
            "- [B](alpha/project_b.md) — b desc\n", encoding="utf-8")

        # frontmatter round trip with escaped quotes
        assert parse_frontmatter(split_frontmatter(
            (know / "beta" / "reference_c.md").read_text(encoding="utf-8"))[0])["description"] == 'c "quoted" desc'

        # migrate: title + description copied, old description with lost words flagged
        changed, flagged = migrate(know)
        assert set(changed) == {"alpha/feedback_a.md", "alpha/project_b.md"}, changed
        assert [f[0] for f in flagged] == ["alpha/feedback_a.md"], flagged
        assert "words" in flagged[0][2]
        fa = (know / "alpha" / "feedback_a.md").read_text(encoding="utf-8")
        assert 'title: "A title"' in fa and 'description: "curated hook for a"' in fa, fa
        assert "keywords: [extra]" in fa and "  type: feedback" in fa       # rest preserved
        assert "body mentions nothing." in fa

        gen = build(know, n_facts=2, n_journal=1, today="2026-02-01")
        assert set(gen) == {"alpha/INDEX.md", "beta/INDEX.md", "MEMORY.md"}, gen.keys()
        a = gen["alpha/INDEX.md"]
        assert a.startswith(HEADER) and "## feedback" in a and "## project" in a
        assert "Triggers: alpha, one, extra" in a                          # fact keywords unioned
        assert "[A title](feedback_a.md) — curated hook for a" in a
        root = gen["MEMORY.md"]
        assert "| Alpha — first topic | alpha, one, extra | [alpha/INDEX.md](alpha/INDEX.md) | 2 |" in root, root
        assert "(no TOPIC.md — add one)" in root                             # beta has none
        assert "- 2026-01-02 — t — two" in root and "- 2026-01-01" not in root
        assert "titles only" not in root                                    # off by default
        t_root = build(know, 2, 1, "2026-02-01", titles=True)["MEMORY.md"]
        assert "- **Alpha:** A title · B" in t_root and "- **beta:** C" in t_root, t_root
        assert root.count("- 2026-02-01 [") == 2                            # no git: today's date

        # write, check clean, drift detected, regenerate byte-identical
        write(know, gen)
        assert check(know, gen) == []
        (know / "MEMORY.md").write_text("hand edit\n", encoding="utf-8")
        assert check(know, build(know, 2, 1, "2026-02-01")) == ["MEMORY.md"]
        write(know, build(know, 2, 1, "2026-02-01"))
        assert (know / "MEMORY.md").read_text(encoding="utf-8") == root

        # per-session journal folder takes over from journal.md, and the rollup joins the build
        (know / "journal").mkdir()
        (know / "journal" / "2026-03-01-0900-x.md").write_text(
            '---\ndate: 2026-03-01\ntime: "09:00"\ntopic: "t"\nsummary: "three"\nnext: "four"\n---\n\nbody\n',
            encoding="utf-8")
        assert journal_entries(know) == ["- 2026-03-01 09:00 t — three. Next: four"]
        gen = build(know, 2, 1, "2026-02-01")
        assert "journal.md" in gen and "three. Next: four" in gen["MEMORY.md"]

        # a hand-maintained mirror index one tier down: routed from the topic index,
        # its keywords unioned into the root row, never generated over
        (know / "alpha" / "kit").mkdir()
        (know / "alpha" / "kit" / "INDEX.md").write_text(
            '---\ntitle: Kit\ndescription: "the kit"\nkeywords: [SOW, kickoff]\nmirrors: "Kit Folder"\n---\n\n# Kit\n- `a.docx` — x\n',
            encoding="utf-8")
        (know / "alpha" / "plain").mkdir()                          # no INDEX.md: not a route
        gen = build(know, 2, 1, "2026-02-01")
        assert "alpha/kit/INDEX.md" not in gen                       # hand-maintained, not regenerated
        a = gen["alpha/INDEX.md"]
        assert "| [Kit](kit/INDEX.md) | SOW, kickoff |" in a and "the kit" not in a, a   # title + triggers only
        assert "plain" not in a
        # hook cutoff: an old project fact is title-only; a feedback fact of any age keeps its hook
        old_p = {"sort_date": "2025-01-01", "date": "2025-01-01", "title": "Old", "description": "hook", "type": "project"}
        old_f = dict(old_p, type="feedback")
        assert fact_line(old_p, "x.md", "2026-02-01", 30) == "- 2025-01-01 [Old](x.md)"
        assert fact_line(old_f, "x.md", "2026-02-01", 30).endswith("— hook")
        assert fact_line(dict(old_p, date=None), "x.md", "2026-02-01", 30).endswith("— hook")   # uncommitted = fresh
        assert "(a fact untouched 30+ days shows its title only" in a
        assert "| alpha, one, extra |" in gen["MEMORY.md"], gen["MEMORY.md"]   # sub keywords stay one tier down
        assert "kit/INDEX.md" not in gen["MEMORY.md"]                # root routes only to topics
        # a topic with initiatives/ gets a generated task roster and a pointer line
        (know / "alpha" / "initiatives").mkdir()
        (know / "alpha" / "initiatives" / "ops.md").write_text(
            "---\ntitle: Ops\n---\n\n## Renew the domain\n- when: Nov\n- status: Not started\n\nthe long story\n", encoding="utf-8")
        gen = build(know, 2, 1, "2026-02-01")
        assert "alpha/TASKS.md" in gen and "| Renew the domain |" in gen["alpha/TASKS.md"], gen.keys()
        assert "the long story" not in gen["alpha/TASKS.md"]          # detail stays one hop down
        assert "Tasks: [TASKS.md](TASKS.md) — generated roster, 1 open in 1 initiatives" in gen["alpha/INDEX.md"]
    print("selftest ok")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--knowledge", help="path to the knowledge/ folder")
    ap.add_argument("--recent-facts", type=int, default=DEFAULTS["n_facts"])
    ap.add_argument("--recent-journal", type=int, default=DEFAULTS["n_journal"])
    ap.add_argument("--hook-days", type=int, default=DEFAULTS["hook_days"],
                    help="project facts untouched longer than this show title-only in the topic index")
    ap.add_argument("--titles", action="store_true", default=DEFAULTS["titles"],
                    help="add an all-titles block to MEMORY.md (recall experiment, Phase 6)")
    ap.add_argument("--check", action="store_true", help="exit 1 if any generated file differs")
    ap.add_argument("--migrate", action="store_true",
                    help="one-time: copy MEMORY.md titles/hooks into fact frontmatter")
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args()
    if a.selftest:
        return selftest()
    if not a.knowledge:
        ap.error("--knowledge is required")
    know = Path(a.knowledge).expanduser()
    if a.migrate:
        changed, flagged = migrate(know)
        print(f"migrated {len(changed)} fact files")
        for rel, old, lost in flagged:
            print(f"REVIEW {rel}\n  old description: {old}\n  words not in hook or body: {', '.join(lost)}")
        return 0
    if not a.check and (know / "journal").is_dir():
        import build_journal
        for stem in build_journal.rescue(know):   # hand-appended journal lines become files
            print(f"rescued hand-appended journal line -> journal/{stem}.md")
    gen = build(know, a.recent_facts, a.recent_journal, dt.date.today().isoformat(), a.titles, a.hook_days)
    if a.check:
        drift = check(know, gen)
        for rel in drift:
            print(f"drift: {rel}")
        print("generated files match sources" if not drift else f"{len(drift)} file(s) stale; run without --check")
        return 1 if drift else 0
    write(know, gen)
    for rel, text in gen.items():
        print(f"wrote {rel}  ({len(text):,} chars, ~{len(text)//4:,} tok)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
